services:
  - type: web
    name: afrolinked-backend
    env: node
    buildCommand: "npm install && npx prisma generate && npx prisma migrate deploy"
    startCommand: "npm run dev"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: afrolinked-db
          property: connectionString
databases:
  - name: afrolinked-db
    engine: postgres
    plan: free
